from django.contrib import admin
from django.urls import include, path, re_path
from base_files.views import *

from Statistics.Sitemap import *
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap,index

from webstory.webstory_sitemap import *;
from .static_sitemap import *
from django.views.generic import TemplateView
from guide.sitemap import Guide_Sitemap

sitemaps = {
    'guide-sitemap':Guide_Sitemap,
    'static':Static_Sitemap,**statistics,
            'fashion-sitemap':FashionView,
            'entertainment-sitemap':EntertainmentView,
            # 'magazine-sitemap':MagazineView,
            # 'news-sitemap':NewsView
            }



urlpatterns = [
     path('ckeditor/', include(
        'ckeditor_uploader.urls')),
    path('guide/', include('guide.urls')),
    path('',home, name='home'),
    path('about-us/',aboutus, name='about-us'),
    path('contact-us/',contactus, name='contact-us'),
    path('disclaimer/',disclaimer, name='disclaimer'),
    path('privacy-policy/',privacy_policy, name='privacy-policy'),
    # path('algebra/',alge, name='alge'),
    
    path('statistics/', include('Statistics.urls')),
    path('web-stories/', include('webstory.urls')),
    
    path('admin/', admin.site.urls),


    ############################# SITEMAP URLS STARTS ######################
    path('sitemap.xml', index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.index'),
    
    # path('algebra.xml', index, {'sitemaps': statistics}, name='django.contrib.sitemaps.views.index'),
    
    path('<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    ############################# SITEMAP URLS STARTS 
    #######################
]
from django.conf import settings
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    


from django.conf import settings

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls)),]


# sitemaps1 = {
#     'static':Static_Sitemap,
#     #Fraction
#     'reduce-fractions-sitemap': Reduce_fraction_Sitemap,
#     'reciprocal-fractions-sitemap': Reciprocal_fraction_Sitemap,
#     'fraction-to-decimal-sitemap': Fraction_decimal_Sitemap,
#     'improper-to-mix-number-sitemap': Improper_mix_Sitemap,
#     'mix-number-to-improper-sitemap': Mix_improper_Sitemap,
#     'addition-fractions-sitemap':Addition_frac_Sitemap,
#     'subtraction-fractions-sitemap':Subtraction_frac_Sitemap,
#     'multiplication-fractions-sitemap':Multiplication_frac_Sitemap,
#     'division-fractions-sitemap':Division_frac_Sitemap,
#     'ratio-to-fraction-sitemap':Fraction_ratio_Sitemap,
#     'squareroot-of-fraction-sitemap':Sqrt_frac_Sitemap,
#     'number-plus-frac-sitemap':Number_plus_frac_Sitemap,
#     'decimal-to-fraction-sitemap': Deci_frac_Sitemap,
#     'percent-to-fraction-sitemap': Percent_frac_Sitemap,
#     'fraction-to-percent-sitemap': Frac_percent_Sitemap,
#     'average-fraction-sitemap': Avg_frac_Sitemap,
#     'mix-numbers-to-percent-sitemap': Mix_percent_Sitemap,
#     'percent-to-decimal-sitemap':Perc_deci_Sitemap,
#     'solve-for-x-sitemap':Solve_X_Sitemap,
#     'ratio-simplifier-sitemap':Ratio_simp_Sitemap,
#     'multiply-3-fractions-sitemap':Multiply_3_frac_Sitemap,
#     'estimate-fractions-sitemap':Estimate_frac_Sitemap,
#     'simplify-fractions-sitemap':Simplify_frac_Sitemap,
#     'complex-fractions-sitemap':Complex_frac_Sitemap,
#     'order-fractions-sitemap':Order_frac_Sitemap,
#     #Exponent
#     'exponent-calculator-sitemap':exponent_Sitemap,
#     
#     #polynomials
#     'polynomials-addition-sitemap':poly_add_Sitemap,
#     'polynomials-subtraction-sitemap':poly_sub_Sitemap,
#     'polynomials-multiplication-sitemap':poly_mul_Sitemap,
#     'polynomials-division-sitemap':poly_div_Sitemap,
#     'is-expression-polynomial-sitemap':check_poly_Sitemap,
#     'degree-of-polynomials-sitemap':degree_poly_Sitemap,
#     'polynomial-in-ascending-order-sitemap':ascding_poly_Sitemap,
#     'polynomial-in-descending-order-sitemap':descding_poly_Sitemap,
#     'leading-polynomials-sitemap':leading_poly_Sitemap,
#     'polynomials-factors-sitemap':fact_poly_Sitemap,
#     'polynomials-gcf-sitemap':gcf_poly_Sitemap,
#     'polynomials-gcf-factors-sitemap':gcf_fact_Sitemap,
#     'polynomials-lcm-sitemap':poly_lcm_Sitemap,
#     'prime-polynomials-sitemap':poly_prime_Sitemap,
#     'polynomials-factor-as-adiition-difference-of-cube-sitemap':poly_fact_cube_Sitemap,
#     'polynomials-factor-as-difference-of-square-sitemap':poly_fact_sqr_Sitemap,
#     'binomial-expansion-sitemap':binom_expn_Sitemap,
#     'polynomials-factor-over-complex-sitemap':fact_complex_Sitemap,
#     'polynomials-root-sitemap':poly_root_Sitemap,
#     'polynomial-remainder-theorm-sitemap':poly_remainder_Sitemap,
#     # math concepts
#     'long-addition-sitemap':long_add_Sitemap,
#     'long-subtraction-sitemap':long_sub_Sitemap,
#     'long-multiplication-sitemap':long_mul_Sitemap,
#     'long-division-sitemap':long_div_Sitemap,
#     'partial-quotient-division-sitemap':partial_div_Sitemap,
#     'age-calculator-sitemap':age_calc_Sitemap,
#     'percentage-change-sitemap':percentage_change_Sitemap,
#     'percentage-value-sitemap':percentage_value_Sitemap,
#     'degree-to-percent-grade-sitemap':degree_to_percent_Sitemap,
#     'percent-grade-to-degree-sitemap':percent_to_degree_Sitemap,
#     #Numbers concepts
#     'even-or-odd-sitemap':even_or_odd_Sitemap,
#     'square-root-sitemap':square_root_Sitemap,
#     'square-sitemap':square_Sitemap,
#     'cube-sitemap':cube_Sitemap,
#     'cube-root-sitemap':cube_root_Sitemap,
#     'divisibility-sitemap':divisibility_Sitemap,
#     'compare-numbers-sitemap':compare_numbers_Sitemap,
#     # decimals concepts
#     'decimal-to-fraction-sitemap':decimal_to_fraction_Sitemap,
#     'adding-decimals-sitemap':add_decimal_Sitemap,
#     'subtracting-decimals-sitemap':sub_decimal_Sitemap,
#     'multiplying-decimals-sitemap':mul_decimal_Sitemap,
#     'dividing-decimals-sitemap':div_decimal_Sitemap,
#     #Rational Numbers
#     'scientific-notation-sitemap':scientific_notation_Sitemap,
#     'expanded-form-sitemap':expanded_form_Sitemap,
#     'sort-numbers-sitemap':sort_numbers_Sitemap,
#     'least-to-greatest-sitemap':least_to_greatest_Sitemap,
#     'greatest-to-least-sitemap':greatest_to_least_Sitemap,
#     'prime-number-sitemap':prime_number_Sitemap,
#     'estimating-sum-sitemap':estimating_sum_Sitemap,
#     'estimating-difference-sitemap':estimating_difference_Sitemap,
#     'additive-inverse-sitemap':additive_inverse_Sitemap,
#     'multiplicative-inverse-sitemap':multiplicative_inverse_Sitemap,
#     # WEIGHT Conversion
#      "grains-to-grams-sitemap":	 Grains_to_grams_sitemap	,
#      "grains-to-kilograms-sitemap":	 Grains_to_kilograms_sitemap	,
#      "grains-to-milligrams-sitemap":	 Grains_to_milligrams_sitemap	,
#      "grains-to-ounces-sitemap":	 Grains_to_ounces_sitemap	,
#      "grains-to-pennyweight-sitemap":	 Grains_to_pennyweight_sitemap	,
#      "grains-to-pounds-sitemap":	 Grains_to_pounds_sitemap	,
#      "grains-to-stone-sitemap":	 Grains_to_stone_sitemap	,
#      "grains-to-long-tons-sitemap":	 Grains_to_long_tons_sitemap	,
#      "grains-to-metric-tons-sitemap":	 Grains_to_metric_tons_sitemap	,
#      "grains-to-troy-ounces-sitemap":	 Grains_to_troy_ounces_sitemap	,
#      "grains-to-troy-pounds-sitemap":	 Grains_to_troy_pounds_sitemap	,
#      "grains-to-tons-sitemap":	 Grains_to_tons_sitemap	,
#      "grams-to-grains-sitemap":	 Grams_to_grains_sitemap	,
#      "grams-to-kilograms-sitemap":	 Grams_to_kilograms_sitemap	,
#      "grams-to-milligrams-sitemap":	 Grams_to_milligrams_sitemap	,
#      "grams-to-ounces-sitemap":	 Grams_to_ounces_sitemap	,
#      "grams-to-pennyweight-sitemap":	 Grams_to_pennyweight_sitemap	,
#      "grams-to-pounds-sitemap":	 Grams_to_pounds_sitemap	,
#      "grams-to-stone-sitemap":	 Grams_to_stone_sitemap	,
#      "grams-to-long-tons-sitemap":	 Grams_to_long_tons_sitemap	,
#      "grams-to-metric-tons-sitemap":	 Grams_to_metric_tons_sitemap	,
#      "grams-to-tons-sitemap":	 Grams_to_tons_sitemap	,
#      "grams-to-troy-ounces-sitemap":	 Grams_to_troy_ounces_sitemap	,
#      "grams-to-troy-pounds-sitemap":	 Grams_to_troy_pounds_sitemap	,
#      "kilograms-to-grains-sitemap":	 Kilograms_to_grains_sitemap	,
#      "kilograms-to-grams-sitemap":	 Kilograms_to_grams_sitemap	,
#      "kilograms-to-milligrams-sitemap":	 Kilograms_to_milligrams_sitemap	,
#      "kilograms-to-ounces-sitemap":	 Kilograms_to_ounces_sitemap	,
#      "kilograms-to-pennyweight-sitemap":	 Kilograms_to_pennyweight_sitemap	,
#      "kilograms-to-pounds-sitemap":	 Kilograms_to_pounds_sitemap	,
#      "kilograms-to-stone-sitemap":	 Kilograms_to_stone_sitemap	,
#      "kilograms-to-long-tons-sitemap":	 Kilograms_to_long_tons_sitemap	,
#      "kilograms-to-metric-tons-sitemap":	 Kilograms_to_metric_tons_sitemap	,
#      "kilograms-to-tons-sitemap":	 Kilograms_to_tons_sitemap	,
#      "kilograms-to-troy-ounces-sitemap":	 Kilograms_to_troy_ounces_sitemap	,
#      "kilograms-to-troy-pounds-sitemap":	 Kilograms_to_troy_pounds_sitemap	,
#      "milligrams-to-grains-sitemap":	 Milligrams_to_grains_sitemap	,
#      "milligrams-to-grams-sitemap":	 Milligrams_to_grams_sitemap	,
#      "milligrams-to-kilograms-sitemap":	 Milligrams_to_kilograms_sitemap	,
#      "milligrams-to-ounces-sitemap":	 Milligrams_to_ounces_sitemap	,
#      "milligrams-to-pennyweight-sitemap":	 Milligrams_to_pennyweight_sitemap	,
#      "milligrams-to-pounds-sitemap":	 Milligrams_to_pounds_sitemap	,
#      "milligrams-to-stone-sitemap":	 Milligrams_to_stone_sitemap	,
#      "milligrams-to-long-tons-sitemap":	 Milligrams_to_long_tons_sitemap	,
#      "milligrams-to-metric-tons-sitemap":	 Milligrams_to_metric_tons_sitemap	,
#      "milligrams-to-tons-sitemap":	 Milligrams_to_tons_sitemap	,
#      "milligrams-to-troy-ounces-sitemap":	 Milligrams_to_troy_ounces_sitemap	,
#      "milligrams-to-troy-pounds-sitemap":	 Milligrams_to_troy_pounds_sitemap	,
#      "ounces-to-grains-sitemap":	 Ounces_to_grains_sitemap	,
#      "ounces-to-grams-sitemap":	 Ounces_to_grams_sitemap	,
#      "ounces-to-kilograms-sitemap":	 Ounces_to_kilograms_sitemap	,
#      "ounces-to-milligrams-sitemap":	 Ounces_to_milligrams_sitemap	,
#      "ounces-to-pennyweight-sitemap":	 Ounces_to_pennyweight_sitemap	,
#      "ounces-to-pounds-sitemap":	 Ounces_to_pounds_sitemap	,
#      "ounces-to-stone-sitemap":	 Ounces_to_stone_sitemap	,
#      "ounces-to-long-tons-sitemap":	 Ounces_to_long_tons_sitemap	,
#      "ounces-to-metric-tons-sitemap":	 Ounces_to_metric_tons_sitemap	,
#      "ounces-to-tons-sitemap":	 Ounces_to_tons_sitemap	,
#      "ounces-to-troy-ounces-sitemap":	 Ounces_to_troy_ounces_sitemap	,
#      "ounces-to-troy-pounds-sitemap":	 Ounces_to_troy_pounds_sitemap	,
#      "pennyweight-to-grains-sitemap":	 Pennyweight_to_grains_sitemap	,
#      "pennyweight-to-grams-sitemap":	 Pennyweight_to_grams_sitemap	,
#      "pennyweight-to-kilograms-sitemap":	 Pennyweight_to_kilograms_sitemap	,
#      "pennyweight-to-milligrams-sitemap":	 Pennyweight_to_milligrams_sitemap	,
#      "pennyweight-to-ounces-sitemap":	 Pennyweight_to_ounces_sitemap	,
#      "pennyweight-to-pounds-sitemap":	 Pennyweight_to_pounds_sitemap	,
#      "pennyweight-to-stone-sitemap":	 Pennyweight_to_stone_sitemap	,
#      "pennyweight-to-long-tons-sitemap":	 Pennyweight_to_long_tons_sitemap	,
#      "pennyweight-to-metric-tons-sitemap":	 Pennyweight_to_metric_tons_sitemap	,
#      "pennyweight-to-tons-sitemap":	 Pennyweight_to_tons_sitemap	,
#      "pennyweight-to-troy-ounces-sitemap":	 Pennyweight_to_troy_ounces_sitemap	,
#      "pennyweight-to-troy-pounds-sitemap":	 Pennyweight_to_troy_pounds_sitemap	,
#      "pounds-to-grains-sitemap":	 Pounds_to_grains_sitemap	,
#      "pounds-to-grams-sitemap":	 Pounds_to_grams_sitemap	,
#      "pounds-to-kilograms-sitemap":	 Pounds_to_kilograms_sitemap	,
#      "pounds-to-milligrams-sitemap":	 Pounds_to_milligrams_sitemap	,
#      "pounds-to-ounces-sitemap":	 Pounds_to_ounces_sitemap	,
#      "pounds-to-pennyweight-sitemap":	 Pounds_to_pennyweight_sitemap	,
#      "pounds-to-stone-sitemap":	 Pounds_to_stone_sitemap	,
#      "pounds-to-long-tons-sitemap":	 Pounds_to_long_tons_sitemap	,
#      "pounds-to-metric-tons-sitemap":	 Pounds_to_metric_tons_sitemap	,
#      "pounds-to-tons-sitemap":	 Pounds_to_tons_sitemap	,
#      "pounds-to-troy-ounces-sitemap":	 Pounds_to_troy_ounces_sitemap	,
#      "pounds-to-troy-pounds-sitemap":	 Pounds_to_troy_pounds_sitemap	,
#      "stone-to-grains-sitemap":	 Stone_to_grains_sitemap	,
#      "stone-to-grams-sitemap":	 Stone_to_grams_sitemap	,
#      "stone-to-kilograms-sitemap":	 Stone_to_kilograms_sitemap	,
#      "stone-to-milligrams-sitemap":	 Stone_to_milligrams_sitemap	,
#      "stone-to-ounces-sitemap":	 Stone_to_ounces_sitemap	,
#      "stone-to-pennyweight-sitemap":	 Stone_to_pennyweight_sitemap	,
#      "stone-to-pounds-sitemap":	 Stone_to_pounds_sitemap	,
#      "stone-to-long-tons-sitemap":	 Stone_to_long_tons_sitemap	,
#      "stone-to-metric-tons-sitemap":	 Stone_to_metric_tons_sitemap	,
#      "stone-to-tons-sitemap":	 Stone_to_tons_sitemap	,
#      "stone-to-troy-ounces-sitemap":	 Stone_to_troy_ounces_sitemap	,
#      "stone-to-troy-pounds-sitemap":	 Stone_to_troy_pounds_sitemap	,
#      "long-tons-to-grains-sitemap":	 Long_Tons_to_grains_sitemap	,
#      "long-tons-to-grams-sitemap":	 Long_Tons_to_grams_sitemap	,
#      "long-tons-to-kilograms-sitemap":	 Long_Tons_to_kilograms_sitemap	,
#      "long-tons-to-milligrams-sitemap":	 Long_Tons_to_milligrams_sitemap	,
#      "long-tons-to-ounces-sitemap":	 Long_Tons_to_ounces_sitemap	,
#      "long-tons-to-pennyweight-sitemap":	 Long_Tons_to_pennyweight_sitemap	,
#      "long-tons-to-pounds-sitemap":	 Long_Tons_to_pounds_sitemap	,
#      "long-tons-to-stone-sitemap":	 Long_Tons_to_stone_sitemap	,
#      "long-tons-to-metric-tons-sitemap":	 Long_Tons_to_metric_tons_sitemap	,
#      "long-tons-to-tons-sitemap":	 Long_Tons_to_tons_sitemap	,
#      "long-tons-to-troy-ounces-sitemap":	 Long_Tons_to_troy_ounces_sitemap	,
#      "long-tons-to-troy-pounds-sitemap":	 Long_Tons_to_troy_pounds_sitemap	,
#      "metric-tons-to-grains-sitemap":	 Metric_Tons_to_grains_sitemap	,
#      "metric-tons-to-grams-sitemap":	 Metric_Tons_to_grams_sitemap	,
#      "metric-tons-to-kilograms-sitemap":	 Metric_Tons_to_kilograms_sitemap	,
#      "metric-tons-to-milligrams-sitemap":	 Metric_Tons_to_milligrams_sitemap	,
#      "metric-tons-to-ounces-sitemap":	 Metric_Tons_to_ounces_sitemap	,
#      "metric-tons-to-pennyweight-sitemap":	 Metric_Tons_to_pennyweight_sitemap	,
#      "metric-tons-to-pounds-sitemap":	 Metric_Tons_to_pounds_sitemap	,
#      "metric-tons-to-stone-sitemap":	 Metric_Tons_to_stone_sitemap	,
#      "metric-tons-to-long-tons-sitemap":	 Metric_Tons_to_long_tons_sitemap	,
#      "metric-tons-to-tons-sitemap":	 Metric_Tons_to_tons_sitemap	,
#      "metric-tons-to-troy-ounces-sitemap":	 Metric_Tons_to_troy_ounces_sitemap	,
#      "metric-tons-to-troy-pounds-sitemap":	 Metric_Tons_to_troy_pounds_sitemap	,
#      "tons-to-grains-sitemap":	 Tons_to_grains_sitemap	,
#      "tons-to-grams-sitemap":	 Tons_to_grams_sitemap	,
#      "tons-to-kilograms-sitemap":	 Tons_to_kilograms_sitemap	,
#      "tons-to-milligrams-sitemap":	 Tons_to_milligrams_sitemap	,
#      "tons-to-ounces-sitemap":	 Tons_to_ounces_sitemap	,
#      "tons-to-pennyweight-sitemap":	 Tons_to_pennyweight_sitemap	,
#      "tons-to-pounds-sitemap":	 Tons_to_pounds_sitemap	,
#      "tons-to-stone-sitemap":	 Tons_to_stone_sitemap	,
#      "tons-to-long-tons-sitemap":	 Tons_to_long_tons_sitemap	,
#      "tons-to-metric-tons-sitemap":	 Tons_to_metric_tons_sitemap	,
#      "tons-to-troy-ounces-sitemap":	 Tons_to_troy_ounces_sitemap	,
#      "tons-to-troy-pounds-sitemap":	 Tons_to_troy_pounds_sitemap	,
#      "troy-ounces-to-grains-sitemap":	 Troy_Ounces_to_grains_sitemap	,
#      "troy-ounces-to-grams-sitemap":	 Troy_Ounces_to_grams_sitemap	,
#      "troy-ounces-to-kilograms-sitemap":	 Troy_Ounces_to_kilograms_sitemap	,
#      "troy-ounces-to-milligrams-sitemap":	 Troy_Ounces_to_milligrams_sitemap	,
#      "troy-ounces-to-ounces-sitemap":	 Troy_Ounces_to_ounces_sitemap	,
#      "troy-ounces-to-pennyweight-sitemap":	 Troy_Ounces_to_pennyweight_sitemap	,
#      "troy-ounces-to-pounds-sitemap":	 Troy_Ounces_to_pounds_sitemap	,
#      "troy-ounces-to-stone-sitemap":	 Troy_Ounces_to_stone_sitemap	,
#      "troy-ounces-to-long-tons-sitemap":	 Troy_Ounces_to_long_tons_sitemap	,
#      "troy-ounces-to-metric-tons-sitemap":	 Troy_Ounces_to_metric_tons_sitemap	,
#      "troy-ounces-to-tons-sitemap":	 Troy_Ounces_to_tons_sitemap	,
#      "troy-ounces-to-troy-pounds-sitemap":	 Troy_Ounces_to_troy_pounds_sitemap	,
#      "troy-pounds-to-grains-sitemap":	 Troy_Pounds_to_grains_sitemap	,
#      "troy-pounds-to-grams-sitemap":	 Troy_Pounds_to_grams_sitemap	,
#      "troy-pounds-to-kilograms-sitemap":	 Troy_Pounds_to_kilograms_sitemap	,
#      "troy-pounds-to-milligrams-sitemap":	 Troy_Pounds_to_milligrams_sitemap	,
#      "troy-pounds-to-ounces-sitemap":	 Troy_Pounds_to_ounces_sitemap	,
#      "troy-pounds-to-pennyweight-sitemap":	 Troy_Pounds_to_pennyweight_sitemap	,
#      "troy-pounds-to-pounds-sitemap":	 Troy_Pounds_to_pounds_sitemap	,
#      "troy-pounds-to-stone-sitemap":	 Troy_Pounds_to_stone_sitemap	,
#      "troy-pounds-to-long-tons-sitemap":	 Troy_Pounds_to_long_tons_sitemap	,
#      "troy-pounds-to-metric-tons-sitemap":	 Troy_Pounds_to_metric_tons_sitemap	,
#      "troy-pounds-to-tons-sitemap":	 Troy_Pounds_to_tons_sitemap	,
#      "troy-pounds-to-troy-ounces-sitemap":	 Troy_Pounds_to_troy_ounces_sitemap	,
#
#     # Temperature Conversions
#      "celsius-to-fahrenheit-sitemap"  : Celsius_to_fahrenheit_model_sitemap ,
#      "celsius-to-kelvin-sitemap"  : Celsius_to_kelvin_model_sitemap ,
#      "fahrenheit-to-celsius-sitemap"  : Fahrenheit_to_celsius_model_sitemap ,
#      "fahrenheit-to-kelvin-sitemap"  : Fahrenheit_to_kelvin_model_sitemap ,
#      "kelvin-to-celsius-sitemap"  : Kelvin_to_celsius_model_sitemap ,
#      "kelvin-to-fahrenheit-sitemap"  : Kelvin_to_fahrenheit_model_sitemap ,
#
#     # Time Conversion
#     'centuries-to-days-sitemap':Centuries_to_days_model_sitemap,
#     'centuries-to-decades-sitemap':Centuries_to_decades_model_sitemap,
#     'centuries-to-hours-sitemap':Centuries_to_hours_model_sitemap,
#     'centuries-to-millenia-sitemap':Centuries_to_millenia_model_sitemap,
#     'centuries-to-microseconds-sitemap':Centuries_to_microseconds_model_sitemap,
#     'centuries-to-milliseconds-sitemap':Centuries_to_milliseconds_model_sitemap,
#     'centuries-to-minutes-sitemap':Centuries_to_minutes_model_sitemap,
#     'centuries-to-months-sitemap':Centuries_to_months_model_sitemap,
#     'centuries-to-nanoseconds-sitemap':Centuries_to_nanoseconds_model_sitemap,
#     'centuries-to-seconds-sitemap':Centuries_to_seconds_model_sitemap,
#     'centuries-to-weeks-sitemap':Centuries_to_weeks_model_sitemap,
#     'centuries-to-work-weeks-sitemap':Centuries_to_work_weeks_model_sitemap,
#     'centuries-to-years-sitemap':Centuries_to_years_model_sitemap,
#     'days-to-centuries-sitemap':Days_to_centuries_model_sitemap,
#     'days-to-decades-sitemap':Days_to_decades_model_sitemap,
#     'days-to-hours-sitemap':Days_to_hours_model_sitemap,
#     'days-to-millenia-sitemap':Days_to_millenia_model_sitemap,
#     'days-to-microseconds-sitemap':Days_to_microseconds_model_sitemap,
#     'days-to-milliseconds-sitemap':Days_to_milliseconds_model_sitemap,
#     'days-to-minutes-sitemap':Days_to_minutes_model_sitemap,
#     'days-to-months-sitemap':Days_to_months_model_sitemap,
#     'days-to-nanoseconds-sitemap':Days_to_nanoseconds_model_sitemap,
#     'days-to-seconds-sitemap':Days_to_seconds_model_sitemap,
#     'days-to-weeks-sitemap':Days_to_weeks_model_sitemap,
#     'days-to-work-weeks-sitemap':Days_to_work_weeks_model_sitemap,
#     'days-to-years-sitemap':Days_to_years_model_sitemap,
#
#     "decades-to-centuries-sitemap" : Decades_to_centuries_model_sitemap ,
#     "decades-to-days-sitemap" : Decades_to_days_model_sitemap ,
#     "decades-to-hours-sitemap" : Decades_to_hours_model_sitemap ,
#     "decades-to-millenia-sitemap" : Decades_to_millenia_model_sitemap ,
#     "decades-to-microseconds-sitemap" : Decades_to_microseconds_model_sitemap ,
#     "decades-to-milliseconds-sitemap" : Decades_to_milliseconds_model_sitemap ,
#     "decades-to-minutes-sitemap" : Decades_to_minutes_model_sitemap ,
#     "decades-to-months-sitemap" : Decades_to_months_model_sitemap ,
#     "decades-to-nanoseconds-sitemap" : Decades_to_nanoseconds_model_sitemap ,
#     "decades-to-seconds-sitemap" : Decades_to_seconds_model_sitemap ,
#     "decades-to-weeks-sitemap" : Decades_to_weeks_model_sitemap ,
#     "decades-to-work-weeks-sitemap" : Decades_to_work_weeks_model_sitemap ,
#     "decades-to-years-sitemap" : Decades_to_years_model_sitemap ,
#     "hours-to-centuries-sitemap" : Hours_to_centuries_model_sitemap ,
#     "hours-to-days-sitemap" : Hours_to_days_model_sitemap ,
#     "hours-to-decades-sitemap" : Hours_to_decades_model_sitemap ,
#     "hours-to-millenia-sitemap" : Hours_to_millenia_model_sitemap ,
#     "hours-to-microseconds-sitemap" : Hours_to_microseconds_model_sitemap ,
#     "hours-to-milliseconds-sitemap" : Hours_to_milliseconds_model_sitemap ,
#     "hours-to-minutes-sitemap" : Hours_to_minutes_model_sitemap ,
#     "hours-to-months-sitemap" : Hours_to_months_model_sitemap ,
#     "hours-to-nanoseconds-sitemap" : Hours_to_nanoseconds_model_sitemap ,
#     "hours-to-seconds-sitemap" : Hours_to_seconds_model_sitemap ,
#     "hours-to-weeks-sitemap" : Hours_to_weeks_model_sitemap ,
#     "hours-to-work-weeks-sitemap" : Hours_to_work_weeks_model_sitemap ,
#     "hours-to-years-sitemap" : Hours_to_years_model_sitemap ,
#     "millenia-to-centuries-sitemap" : Millenia_to_centuries_model_sitemap ,
#     "millenia-to-days-sitemap" : Millenia_to_days_model_sitemap ,
#     "millenia-to-decades-sitemap" : Millenia_to_decades_model_sitemap ,
#     "millenia-to-hours-sitemap" : Millenia_to_hours_model_sitemap ,
#     "millenia-to-microseconds-sitemap" : Millenia_to_microseconds_model_sitemap ,
#     "millenia-to-milliseconds-sitemap" : Millenia_to_milliseconds_model_sitemap ,
#     "millenia-to-minutes-sitemap" : Millenia_to_minutes_model_sitemap ,
#     "millenia-to-months-sitemap" : Millenia_to_months_model_sitemap ,
#     "millenia-to-nanoseconds-sitemap" : Millenia_to_nanoseconds_model_sitemap ,
#     "millenia-to-seconds-sitemap" : Millenia_to_seconds_model_sitemap ,
#     "millenia-to-weeks-sitemap" : Millenia_to_weeks_model_sitemap ,
#     "millenia-to-work-weeks-sitemap" : Millenia_to_work_weeks_model_sitemap ,
#     "millenia-to-years-sitemap" : Millenia_to_years_model_sitemap ,
#     "microseconds-to-centuries-sitemap" : Microseconds_to_centuries_model_sitemap ,
#     "microseconds-to-days-sitemap" : Microseconds_to_days_model_sitemap ,
#     "microseconds-to-decades-sitemap" : Microseconds_to_decades_model_sitemap ,
#     "microseconds-to-hours-sitemap" : Microseconds_to_hours_model_sitemap ,
#     "microseconds-to-millenia-sitemap" : Microseconds_to_millenia_model_sitemap ,
#     "microseconds-to-milliseconds-sitemap" : Microseconds_to_milliseconds_model_sitemap ,
#     "microseconds-to-minutes-sitemap" : Microseconds_to_minutes_model_sitemap ,
#     "microseconds-to-months-sitemap" : Microseconds_to_months_model_sitemap ,
#     "microseconds-to-nanoseconds-sitemap" : Microseconds_to_nanoseconds_model_sitemap ,
#     "microseconds-to-seconds-sitemap" : Microseconds_to_seconds_model_sitemap ,
#     "microseconds-to-weeks-sitemap" : Microseconds_to_weeks_model_sitemap ,
#     "microseconds-to-work-weeks-sitemap" : Microseconds_to_work_weeks_model_sitemap ,
#     "microseconds-to-years-sitemap" : Microseconds_to_years_model_sitemap ,
#     "milliseconds-to-centuries-sitemap" : Milliseconds_to_centuries_model_sitemap ,
#     "milliseconds-to-days-sitemap" : Milliseconds_to_days_model_sitemap ,
#     "milliseconds-to-decades-sitemap" : Milliseconds_to_decades_model_sitemap ,
#     "milliseconds-to-hours-sitemap" : Milliseconds_to_hours_model_sitemap ,
#     "milliseconds-to-millenia-sitemap" : Milliseconds_to_millenia_model_sitemap ,
#     "milliseconds-to-microseconds-sitemap" : Milliseconds_to_microseconds_model_sitemap ,
#     "milliseconds-to-minutes-sitemap" : Milliseconds_to_minutes_model_sitemap ,
#     "milliseconds-to-months-sitemap" : Milliseconds_to_months_model_sitemap ,
#     "milliseconds-to-nanoseconds-sitemap" : Milliseconds_to_nanoseconds_model_sitemap ,
#     "milliseconds-to-seconds-sitemap" : Milliseconds_to_seconds_model_sitemap ,
#     "milliseconds-to-weeks-sitemap" : Milliseconds_to_weeks_model_sitemap ,
#     "milliseconds-to-work-weeks-sitemap" : Milliseconds_to_work_weeks_model_sitemap ,
#     "milliseconds-to-years-sitemap" : Milliseconds_to_years_model_sitemap ,
#     "minutes-to-centuries-sitemap" : Minutes_to_centuries_model_sitemap ,
#      "minutes-to-days-sitemap" : Minutes_to_days_model_sitemap ,
#      "minutes-to-decades-sitemap" : Minutes_to_decades_model_sitemap ,
#      "minutes-to-hours-sitemap" : Minutes_to_hours_model_sitemap ,
#      "minutes-to-millenia-sitemap" : Minutes_to_millenia_model_sitemap ,
#      "minutes-to-microseconds-sitemap" : Minutes_to_microseconds_model_sitemap ,
#      "minutes-to-milliseconds-sitemap" : Minutes_to_milliseconds_model_sitemap ,
#      "minutes-to-months-sitemap" : Minutes_to_months_model_sitemap ,
#      "minutes-to-nanoseconds-sitemap" : Minutes_to_nanoseconds_model_sitemap ,
#      "minutes-to-seconds-sitemap" : Minutes_to_seconds_model_sitemap ,
#      "minutes-to-weeks-sitemap" : Minutes_to_weeks_model_sitemap ,
#      "minutes-to-work-weeks-sitemap" : Minutes_to_work_weeks_model_sitemap ,
#      "minutes-to-years-sitemap" : Minutes_to_years_model_sitemap ,
#      "months-to-centuries-model-sitemap" : Months_to_centuries_model_sitemap ,
#      "months-to-days-model-sitemap" : Months_to_days_model_sitemap ,
#      "months-to-decades-model-sitemap" : Months_to_decades_model_sitemap ,
#      "months-to-hours-model-sitemap" : Months_to_hours_model_sitemap ,
#      "months-to-millenia-model-sitemap" : Months_to_millenia_model_sitemap ,
#      "months-to-microseconds-model-sitemap" : Months_to_microseconds_model_sitemap ,
#      "months-to-milliseconds-model-sitemap" : Months_to_milliseconds_model_sitemap ,
#      "months-to-minutes-model-sitemap" : Months_to_minutes_model_sitemap ,
#      "months-to-nanoseconds-model-sitemap" : Months_to_nanoseconds_model_sitemap ,
#      "months-to-seconds-model-sitemap" : Months_to_seconds_model_sitemap ,
#      "months-to-weeks-model-sitemap" : Months_to_weeks_model_sitemap ,
#      "months-to-work-weeks-model-sitemap" : Months_to_work_weeks_model_sitemap ,
#      "months-to-years-model-sitemap" : Months_to_years_model_sitemap ,
#      "nanoseconds-to-centuries-sitemap" : Nanoseconds_to_centuries_model_sitemap ,
#      "nanoseconds-to-days-sitemap" : Nanoseconds_to_days_model_sitemap ,
#      "nanoseconds-to-decades-sitemap" : Nanoseconds_to_decades_model_sitemap ,
#      "nanoseconds-to-hours-sitemap" : Nanoseconds_to_hours_model_sitemap ,
#      "nanoseconds-to-millenia-sitemap" : Nanoseconds_to_millenia_model_sitemap ,
#      "nanoseconds-to-microseconds-sitemap" : Nanoseconds_to_microseconds_model_sitemap ,
#      "nanoseconds-to-milliseconds-sitemap" : Nanoseconds_to_milliseconds_model_sitemap ,
#      "nanoseconds-to-minutes-sitemap" : Nanoseconds_to_minutes_model_sitemap ,
#      "nanoseconds-to-months-sitemap" : Nanoseconds_to_months_model_sitemap ,
#      "nanoseconds-to-seconds-sitemap" : Nanoseconds_to_seconds_model_sitemap ,
#      "nanoseconds-to-weeks-sitemap" : Nanoseconds_to_weeks_model_sitemap ,
#      "nanoseconds-to-work-weeks-sitemap" : Nanoseconds_to_work_weeks_model_sitemap ,
#      "nanoseconds-to-years-sitemap" : Nanoseconds_to_years_model_sitemap ,
#      "seconds-to-centuries-sitemap" : Seconds_to_centuries_model_sitemap ,
#      "seconds-to-days-sitemap" : Seconds_to_days_model_sitemap ,
#      "seconds-to-decades-sitemap" : Seconds_to_decades_model_sitemap ,
#      "seconds-to-hours-sitemap" : Seconds_to_hours_model_sitemap ,
#      "seconds-to-millenia-sitemap" : Seconds_to_millenia_model_sitemap ,
#      "seconds-to-microseconds-sitemap" : Seconds_to_microseconds_model_sitemap ,
#      "seconds-to-milliseconds-sitemap" : Seconds_to_milliseconds_model_sitemap ,
#      "seconds-to-minutes-sitemap" : Seconds_to_minutes_model_sitemap ,
#      "seconds-to-months-sitemap" : Seconds_to_months_model_sitemap ,
#      "seconds-to-nanoseconds-sitemap" : Seconds_to_nanoseconds_model_sitemap ,
#      "seconds-to-weeks-sitemap" : Seconds_to_weeks_model_sitemap ,
#      "seconds-to-work-weeks-sitemap" : Seconds_to_work_weeks_model_sitemap ,
#      "seconds-to-years-sitemap" : Seconds_to_years_model_sitemap ,
#      "weeks-to-centuries-sitemap" : Weeks_to_centuries_model_sitemap ,
#      "weeks-to-days-sitemap" : Weeks_to_days_model_sitemap ,
#      "weeks-to-decades-sitemap" : Weeks_to_decades_model_sitemap ,
#      "weeks-to-hours-sitemap" : Weeks_to_hours_model_sitemap ,
#      "weeks-to-millenia-sitemap" : Weeks_to_millenia_model_sitemap ,
#      "weeks-to-microseconds-sitemap" : Weeks_to_microseconds_model_sitemap ,
#      "weeks-to-milliseconds-sitemap" : Weeks_to_milliseconds_model_sitemap ,
#      "weeks-to-minutes-sitemap" : Weeks_to_minutes_model_sitemap ,
#      "weeks-to-months-sitemap" : Weeks_to_months_model_sitemap ,
#      "weeks-to-nanoseconds-sitemap" : Weeks_to_nanoseconds_model_sitemap ,
#      "weeks-to-seconds-sitemap" : Weeks_to_seconds_model_sitemap ,
#      "weeks-to-work-weeks-sitemap" : Weeks_to_work_weeks_model_sitemap ,
#      "weeks-to-years-sitemap" : Weeks_to_years_model_sitemap ,
#      "years-to-centuries-sitemap" : Years_to_centuries_model_sitemap ,
#      "years-to-days-sitemap" : Years_to_days_model_sitemap ,
#      "years-to-decades-sitemap" : Years_to_decades_model_sitemap ,
#      "years-to-hours-sitemap" : Years_to_hours_model_sitemap ,
#      "years-to-millenia-sitemap" : Years_to_millenia_model_sitemap ,
#      "years-to-microseconds-sitemap" : Years_to_microseconds_model_sitemap ,
#      "years-to-milliseconds-sitemap" : Years_to_milliseconds_model_sitemap ,
#      "years-to-minutes-sitemap" : Years_to_minutes_model_sitemap ,
#      "years-to-months-sitemap" : Years_to_months_model_sitemap ,
#      "years-to-nanoseconds-sitemap" : Years_to_nanoseconds_model_sitemap ,
#      "years-to-seconds-sitemap" : Years_to_seconds_model_sitemap ,
#      "years-to-weeks-sitemap" : Years_to_weeks_model_sitemap ,
#      "years-to-work-weeks-sitemap" : Years_to_work_weeks_model_sitemap ,
#      "work-weeks-to-centuries-sitemap": Work_weeks_to_centuries_model_sitemap,
#      "work-weeks-to-days-sitemap": Work_weeks_to_days_model_sitemap,
#      "work-weeks-to-decades-sitemap": Work_weeks_to_decades_model_sitemap,
#      "work-weeks-to-hours-sitemap": Work_weeks_to_hours_model_sitemap,
#      "work-weeks-to-millenia-sitemap": Work_weeks_to_millenia_model_sitemap,
#      "work-weeks-to-microseconds-sitemap": Work_weeks_to_microseconds_model_sitemap,
#      "work-weeks-to-milliseconds-sitemap": Work_weeks_to_milliseconds_model_sitemap,
#      "work-weeks-to-minutes-sitemap": Work_weeks_to_minutes_model_sitemap,
#      "work-weeks-to-months-sitemap": Work_weeks_to_months_model_sitemap,
#      "work-weeks-to-nanoseconds-sitemap": Work_weeks_to_nanoseconds_model_sitemap,
#      "work-weeks-to-seconds-sitemap": Work_weeks_to_seconds_model_sitemap,
#      "work-weeks-to-weeks-sitemap": Work_weeks_to_weeks_model_sitemap,
#      "work-weeks-to-years-sitemap": Work_weeks_to_years_model_sitemap,
#      "hours-minutes-seconds-to-hours-sitemap" : Hours_minutes_seconds_to_hours_model_sitemap,
#      "hours-minutes-seconds-to-minutes-sitemap" : Hours_minutes_seconds_to_minutes_model_sitemap ,
#      "hours-minutes-seconds-to-seconds-sitemap" : Hours_minutes_seconds_to_seconds_model_sitemap ,
#     "seconds-to-hours-minutes-seconds-model-sitemap" : Seconds_to_hours_minutes_seconds_model_sitemap,
#     "hours-to-hours-minutes-seconds-model-sitemap"   : Hours_to_hours_minutes_seconds_model_sitemap,
#     "minutes-to-hours-minutes-seconds-model-sitemap" : Minutes_to_hours_minutes_seconds_model_sitemap,
#
#     ######### HEIGHT CONVERSIONS ########
#     "centimeters-to-feet-inches-sitemap" : Centimeters_to_feet_inches_model_Sitemap ,
#     "feet-inches-to-centimeters-sitemap" : Feet_inches_to_centimeters_model_Sitemap ,
#
#     ############### PHYSICS SITEMAPS
#     "velocity-by-distance-sitemap":Velocity_by_distance_sitemap,
#     "velocity-by-acceleration-sitemap":Velocity_by_acceleration_sitemap,
#     "average-velocity-sitemap":Avg_velocity_sitemap,
#     "acceleration-sitemap":acceleration_sitemap,
#     "torque-sitemap":Torque_sitemap,
#     "density-sitemap":Density_sitemap,
#     "water-pressure-sitemap":Water_pressure_sitemap,
#     "friction-sitemap" : Friction_model_sitemap,
#     "wavelength-sitemap" : Wavelength_model_sitemap,
#     "gravity-sitemap":Gravitational_force_Model_sitemap,
#     "acceleration-due-to-gravity-sitemap":Acceleration_due_to_gravity_Model_sitemap,
#     "specific-gravity-sitemap":Specific_gravity_Model_sitemap,
#     "stress-sitemap":Stress_model_sitemap,
#     "strain-sitemap":Strain_model_sitemap,
#     "youngs-modulus-by-stress-strain-sitemap":Young_modulus_by_stress_strain_model_sitemap,
#     "young-modulus-multiple-input-sitemap":Young_modulus_multiple_input_model_sitemap,
#     "uniform-accelerated-motion-sitemap" : Uniform_find_a_t_model_model_sitemap,
#     "gravitational-potential-energy-sitemap":Gravitational_potential_energy_sitemap,
#     "kinetic-energy-sitemap":Kinetic_energy_sitemap,
#     "momentum-sitemap":Momentum_sitemap,
#     "force-sitemap":Force_sitemap,
# }